CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID                NUMBER(19,0)              NOT NULL,
    VERSION                        NUMBER(19,0),
    JOB_NAME                       VARCHAR2(100 CHAR)        NOT NULL,
    JOB_KEY                        VARCHAR2(32 CHAR)         NOT NULL
);

ALTER TABLE BATCH_JOB_INSTANCE ADD CONSTRAINT JOB_INST_PK PRIMARY KEY (JOB_INSTANCE_ID);

ALTER TABLE BATCH_JOB_INSTANCE ADD CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY);

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID               NUMBER(19,0)              NOT NULL,
    VERSION                        NUMBER(19,0),
    JOB_INSTANCE_ID                NUMBER(19,0)              NOT NULL,
    CREATE_TIME                    TIMESTAMP                 NOT NULL,
    START_TIME                     TIMESTAMP                 DEFAULT NULL,
    END_TIME                       TIMESTAMP                 DEFAULT NULL,
    STATUS                         VARCHAR2(10 CHAR),
    EXIT_CODE                      VARCHAR2(2500 CHAR),
    EXIT_MESSAGE                   VARCHAR2(2500 CHAR),
    LAST_UPDATED                   TIMESTAMP,
    JOB_CONFIGURATION_LOCATION     VARCHAR2(2500 CHAR)
);

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INST_EXEC_PK PRIMARY KEY (JOB_EXECUTION_ID);

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID               NUMBER(19,0)              NOT NULL,
    TYPE_CD                        VARCHAR2(6 CHAR)          NOT NULL,
    KEY_NAME                       VARCHAR2(100 CHAR)        NOT NULL,
    STRING_VAL                     VARCHAR2(250 CHAR),
    DATE_VAL                       TIMESTAMP                 DEFAULT NULL,
    LONG_VAL                       NUMBER(19,0),
    DOUBLE_VAL                     DOUBLE PRECISION,
    IDENTIFYING                    CHAR(1 CHAR)              NOT NULL
);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID              NUMBER(19,0)              NOT NULL,
    VERSION                        NUMBER(19,0)              NOT NULL,
    STEP_NAME                      VARCHAR2(100 CHAR)        NOT NULL,
    JOB_EXECUTION_ID               NUMBER(19,0)              NOT NULL,
    START_TIME                     TIMESTAMP                 NOT NULL,
    END_TIME                       TIMESTAMP                 DEFAULT NULL,
    STATUS                         VARCHAR2(10 CHAR),
    COMMIT_COUNT                   NUMBER(19,0),
    READ_COUNT                     NUMBER(19,0),
    FILTER_COUNT                   NUMBER(19,0),
    WRITE_COUNT                    NUMBER(19,0),
    READ_SKIP_COUNT                NUMBER(19,0),
    WRITE_SKIP_COUNT               NUMBER(19,0),
    PROCESS_SKIP_COUNT             NUMBER(19,0),
    ROLLBACK_COUNT                 NUMBER(19,0),
    EXIT_CODE                      VARCHAR2(2500 CHAR),
    EXIT_MESSAGE                   VARCHAR2(2500 CHAR),
    LAST_UPDATED                   TIMESTAMP
);

ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXEC_STEP_PK PRIMARY KEY (STEP_EXECUTION_ID);

ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID              NUMBER(19,0)              NOT NULL,
    SHORT_CONTEXT                  VARCHAR2(2500 CHAR)       NOT NULL,
    SERIALIZED_CONTEXT             CLOB
);

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_PK PRIMARY KEY (STEP_EXECUTION_ID);

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID               NUMBER(19,0)              NOT NULL,
    SHORT_CONTEXT                  VARCHAR2(2500 CHAR)       NOT NULL,
    SERIALIZED_CONTEXT             CLOB
);

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_PK PRIMARY KEY (JOB_EXECUTION_ID);

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NOCYCLE;

CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NOCYCLE;

CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NOCYCLE;

