DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT CASCADE;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT CASCADE;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION CASCADE;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS CASCADE;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION CASCADE;

DROP TABLE IF EXISTS BATCH_JOB_INSTANCE CASCADE;

DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;

DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;

DROP SEQUENCE BATCH_JOB_SEQ;

