DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT /*CASCADE CONSTRAINTS*/;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT /*CASCADE CONSTRAINTS*/;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION /*CASCADE CONSTRAINTS*/;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS /*CASCADE CONSTRAINTS*/;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION /*CASCADE CONSTRAINTS*/;

DROP TABLE IF EXISTS BATCH_JOB_INSTANCE /*CASCADE CONSTRAINTS*/;

