CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID                BIGINT                    NOT NULL,
    VERSION                        BIGINT,
    JOB_NAME                       VARCHAR(100)              NOT NULL,
    JOB_KEY                        VARCHAR(32)               NOT NULL
);

ALTER TABLE BATCH_JOB_INSTANCE ADD CONSTRAINT JOB_INST_PK PRIMARY KEY (JOB_INSTANCE_ID);

ALTER TABLE BATCH_JOB_INSTANCE ADD CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY);

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID               BIGINT                    NOT NULL,
    VERSION                        BIGINT,
    JOB_INSTANCE_ID                BIGINT                    NOT NULL,
    CREATE_TIME                    DATETIME                  NOT NULL,
    START_TIME                     DATETIME                  DEFAULT NULL,
    END_TIME                       DATETIME                  DEFAULT NULL,
    STATUS                         VARCHAR(10),
    EXIT_CODE                      VARCHAR(2500),
    EXIT_MESSAGE                   VARCHAR(2500),
    LAST_UPDATED                   DATETIME,
    JOB_CONFIGURATION_LOCATION     VARCHAR(2500)
);

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INST_EXEC_PK PRIMARY KEY (JOB_EXECUTION_ID);

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID               BIGINT                    NOT NULL,
    TYPE_CD                        VARCHAR(6)                NOT NULL,
    KEY_NAME                       VARCHAR(100)              NOT NULL,
    STRING_VAL                     VARCHAR(250),
    DATE_VAL                       DATETIME                  DEFAULT NULL,
    LONG_VAL                       BIGINT,
    DOUBLE_VAL                     DOUBLE PRECISION,
    IDENTIFYING                    CHAR(1)                   NOT NULL
);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID              BIGINT                    NOT NULL,
    VERSION                        BIGINT                    NOT NULL,
    STEP_NAME                      VARCHAR(100)              NOT NULL,
    JOB_EXECUTION_ID               BIGINT                    NOT NULL,
    START_TIME                     DATETIME                  NOT NULL,
    END_TIME                       DATETIME                  DEFAULT NULL,
    STATUS                         VARCHAR(10),
    COMMIT_COUNT                   BIGINT,
    READ_COUNT                     BIGINT,
    FILTER_COUNT                   BIGINT,
    WRITE_COUNT                    BIGINT,
    READ_SKIP_COUNT                BIGINT,
    WRITE_SKIP_COUNT               BIGINT,
    PROCESS_SKIP_COUNT             BIGINT,
    ROLLBACK_COUNT                 BIGINT,
    EXIT_CODE                      VARCHAR(2500),
    EXIT_MESSAGE                   VARCHAR(2500),
    LAST_UPDATED                   DATETIME
);

ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXEC_STEP_PK PRIMARY KEY (STEP_EXECUTION_ID);

ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID              BIGINT                    NOT NULL,
    SHORT_CONTEXT                  VARCHAR(2500)             NOT NULL,
    SERIALIZED_CONTEXT             LONGTEXT
);

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_PK PRIMARY KEY (STEP_EXECUTION_ID);

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID               BIGINT                    NOT NULL,
    SHORT_CONTEXT                  VARCHAR(2500)             NOT NULL,
    SERIALIZED_CONTEXT             LONGTEXT
);

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_PK PRIMARY KEY (JOB_EXECUTION_ID);

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);

