CREATE TABLE ACT_GE_PROPERTY
(
    NAME_                          NVARCHAR(64),
    VALUE_                         NVARCHAR(300),
    REV_                           INT,
    CONSTRAINT ACT_GE_PROPERTY_PK PRIMARY KEY (NAME_)
) ENGINE=InnoDB;

CREATE TABLE ACT_GE_BYTEARRAY
(
    ID_                            NVARCHAR(64),
    REV_                           INT,
    NAME_                          NVARCHAR(255),
    DEPLOYMENT_ID_                 NVARCHAR(64),
    BYTES_                         LONGBLOB,
    GENERATED_                     BIT,
    CONSTRAINT ACT_GE_BYTEARRAY_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RE_DEPLOYMENT
(
    ID_                            NVARCHAR(64),
    NAME_                          NVARCHAR(255),
    CATEGORY_                      NVARCHAR(255),
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    DEPLOY_TIME_                   DATETIME,
    CONSTRAINT ACT_RE_DEPLOYMENT_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RE_MODEL
(
    ID_                            NVARCHAR(64)              NOT NULL,
    REV_                           INT,
    NAME_                          NVARCHAR(255),
    KEY_                           NVARCHAR(255),
    CATEGORY_                      NVARCHAR(255),
    CREATE_TIME_                   DATETIME,
    LAST_UPDATE_TIME_              DATETIME,
    VERSION_                       INT,
    META_INFO_                     LONGTEXT,
    DEPLOYMENT_ID_                 NVARCHAR(64),
    EDITOR_SOURCE_VALUE_ID_        NVARCHAR(64),
    EDITOR_SOURCE_EXTRA_VALUE_ID_  NVARCHAR(64),
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    CONSTRAINT ACT_RE_MODEL_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RU_EXECUTION
(
    ID_                            NVARCHAR(64),
    REV_                           INT,
    PROC_INST_ID_                  NVARCHAR(64),
    BUSINESS_KEY_                  NVARCHAR(255),
    PARENT_ID_                     NVARCHAR(64),
    PROC_DEF_ID_                   NVARCHAR(64),
    SUPER_EXEC_                    NVARCHAR(64),
    ACT_ID_                        NVARCHAR(255),
    IS_ACTIVE_                     BIT,
    IS_CONCURRENT_                 BIT,
    IS_SCOPE_                      BIT,
    IS_EVENT_SCOPE_                BIT,
    SUSPENSION_STATE_              INT,
    CACHED_ENT_STATE_              INT,
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    NAME_                          NVARCHAR(255),
    LOCK_TIME_                     DATETIME,
    CONSTRAINT ACT_RU_EXECUTION_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RU_JOB
(
    ID_                            NVARCHAR(64)              NOT NULL,
    REV_                           INT,
    TYPE_                          NVARCHAR(255)             NOT NULL,
    LOCK_EXP_TIME_                 DATETIME,
    LOCK_OWNER_                    NVARCHAR(255),
    EXCLUSIVE_                     BIT,
    EXECUTION_ID_                  NVARCHAR(64),
    PROCESS_INSTANCE_ID_           NVARCHAR(64),
    PROC_DEF_ID_                   NVARCHAR(64),
    RETRIES_                       INT,
    EXCEPTION_STACK_ID_            NVARCHAR(64),
    EXCEPTION_MSG_                 LONGTEXT,
    DUEDATE_                       DATETIME,
    REPEAT_                        NVARCHAR(255),
    HANDLER_TYPE_                  NVARCHAR(255),
    HANDLER_CFG_                   LONGTEXT,
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    CONSTRAINT ACT_RU_JOB_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RE_PROCDEF
(
    ID_                            NVARCHAR(64)              NOT NULL,
    REV_                           INT,
    CATEGORY_                      NVARCHAR(255),
    NAME_                          NVARCHAR(255),
    KEY_                           NVARCHAR(255)             NOT NULL,
    VERSION_                       INT                       NOT NULL,
    DEPLOYMENT_ID_                 NVARCHAR(64),
    RESOURCE_NAME_                 LONGTEXT,
    DGRM_RESOURCE_NAME_            LONGTEXT,
    DESCRIPTION_                   LONGTEXT,
    HAS_START_FORM_KEY_            BIT,
    HAS_GRAPHICAL_NOTATION_        BIT,
    SUSPENSION_STATE_              INT,
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    CONSTRAINT ACT_RE_PROCDEF_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RU_TASK
(
    ID_                            NVARCHAR(64),
    REV_                           INT,
    EXECUTION_ID_                  NVARCHAR(64),
    PROC_INST_ID_                  NVARCHAR(64),
    PROC_DEF_ID_                   NVARCHAR(64),
    NAME_                          NVARCHAR(255),
    PARENT_TASK_ID_                NVARCHAR(64),
    DESCRIPTION_                   LONGTEXT,
    TASK_DEF_KEY_                  NVARCHAR(255),
    OWNER_                         NVARCHAR(255),
    ASSIGNEE_                      NVARCHAR(255),
    DELEGATION_                    NVARCHAR(64),
    PRIORITY_                      INT,
    CREATE_TIME_                   DATETIME,
    DUE_DATE_                      DATETIME,
    CATEGORY_                      NVARCHAR(255),
    SUSPENSION_STATE_              INT,
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    FORM_KEY_                      NVARCHAR(255),
    CONSTRAINT ACT_RU_TASK_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RU_IDENTITYLINK
(
    ID_                            NVARCHAR(64),
    REV_                           INT,
    GROUP_ID_                      NVARCHAR(255),
    TYPE_                          NVARCHAR(255),
    USER_ID_                       NVARCHAR(255),
    TASK_ID_                       NVARCHAR(64),
    PROC_INST_ID_                  NVARCHAR(64),
    PROC_DEF_ID_                   NVARCHAR(64),
    CONSTRAINT ACT_RU_IDENTITYLINK_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RU_VARIABLE
(
    ID_                            NVARCHAR(64)              NOT NULL,
    REV_                           INT,
    TYPE_                          NVARCHAR(255)             NOT NULL,
    NAME_                          NVARCHAR(255)             NOT NULL,
    EXECUTION_ID_                  NVARCHAR(64),
    PROC_INST_ID_                  NVARCHAR(64),
    TASK_ID_                       NVARCHAR(64),
    BYTEARRAY_ID_                  NVARCHAR(64),
    DOUBLE_                        DOUBLE PRECISION,
    LONG_                          BIGINT,
    TEXT_                          LONGTEXT,
    TEXT2_                         LONGTEXT,
    CONSTRAINT ACT_RU_VARIABLE_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_RU_EVENT_SUBSCR
(
    ID_                            NVARCHAR(64)              NOT NULL,
    REV_                           INT,
    EVENT_TYPE_                    NVARCHAR(255)             NOT NULL,
    EVENT_NAME_                    NVARCHAR(255),
    EXECUTION_ID_                  NVARCHAR(64),
    PROC_INST_ID_                  NVARCHAR(64),
    ACTIVITY_ID_                   NVARCHAR(64),
    CONFIGURATION_                 NVARCHAR(255),
    CREATED_                       DATETIME                  NOT NULL,
    PROC_DEF_ID_                   NVARCHAR(64),
    TENANT_ID_                     NVARCHAR(255)             DEFAULT '',
    CONSTRAINT ACT_RU_EVENT_SUBSCR_PK PRIMARY KEY (ID_)
) ENGINE=InnoDB;

CREATE TABLE ACT_EVT_LOG
(
    LOG_NR_                        BIGINT                   AUTO_INCREMENT,
    TYPE_                          NVARCHAR(64),
    PROC_DEF_ID_                   NVARCHAR(64),
    PROC_INST_ID_                  NVARCHAR(64),
    EXECUTION_ID_                  NVARCHAR(64),
    TASK_ID_                       NVARCHAR(64),
    TIME_STAMP_                    DATETIME                  NOT NULL,
    USER_ID_                       NVARCHAR(255),
    DATA_                          LONGBLOB,
    LOCK_OWNER_                    NVARCHAR(255),
    LOCK_TIME_                     DATETIME,
    IS_PROCESSED_                  SMALLINT                  DEFAULT 0,
    CONSTRAINT ACT_EVT_LOG_PK PRIMARY KEY (LOG_NR_)
) ENGINE=InnoDB;

CREATE INDEX ACT_IDX_EXEC_BUSKEY ON ACT_RU_EXECUTION (BUSINESS_KEY_);

CREATE INDEX ACT_IDX_TASK_CREATE ON ACT_RU_TASK (CREATE_TIME_);

CREATE INDEX ACT_IDX_IDENT_LNK_USER ON ACT_RU_IDENTITYLINK (USER_ID_);

CREATE INDEX ACT_IDX_IDENT_LNK_GROUP ON ACT_RU_IDENTITYLINK (GROUP_ID_);

CREATE INDEX ACT_IDX_EVENT_SUBSCR_CONFIG_ ON ACT_RU_EVENT_SUBSCR (CONFIGURATION_);

CREATE INDEX ACT_IDX_VARIABLE_TASK_ID ON ACT_RU_VARIABLE (TASK_ID_);

CREATE INDEX ACT_IDX_BYTEAR_DEPL ON ACT_GE_BYTEARRAY (DEPLOYMENT_ID_);

ALTER TABLE ACT_GE_BYTEARRAY ADD CONSTRAINT ACT_FK_BYTEARR_DEPL FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES ACT_RE_DEPLOYMENT (ID_);

ALTER TABLE ACT_RE_PROCDEF ADD CONSTRAINT ACT_UNIQ_PROCDEF UNIQUE (KEY_, VERSION_, TENANT_ID_);

CREATE INDEX ACT_IDX_EXE_PROCINST ON ACT_RU_EXECUTION (PROC_INST_ID_);

ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_EXE_PARENT ON ACT_RU_EXECUTION (PARENT_ID_);

ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_PARENT FOREIGN KEY (PARENT_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_EXE_SUPER ON ACT_RU_EXECUTION (SUPER_EXEC_);

ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_SUPER FOREIGN KEY (SUPER_EXEC_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_EXE_PROCDEF ON ACT_RU_EXECUTION (PROC_DEF_ID_);

ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_PROCDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);

CREATE INDEX ACT_IDX_TSKASS_TASK ON ACT_RU_IDENTITYLINK (TASK_ID_);

ALTER TABLE ACT_RU_IDENTITYLINK ADD CONSTRAINT ACT_FK_TSKASS_TASK FOREIGN KEY (TASK_ID_) REFERENCES ACT_RU_TASK (ID_);

CREATE INDEX ACT_IDX_ATHRZ_PROCEDEF ON ACT_RU_IDENTITYLINK (PROC_DEF_ID_);

ALTER TABLE ACT_RU_IDENTITYLINK ADD CONSTRAINT ACT_FK_ATHRZ_PROCEDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);

CREATE INDEX ACT_IDX_IDL_PROCINST ON ACT_RU_IDENTITYLINK (PROC_INST_ID_);

ALTER TABLE ACT_RU_IDENTITYLINK ADD CONSTRAINT ACT_FK_IDL_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_TASK_EXEC ON ACT_RU_TASK (EXECUTION_ID_);

ALTER TABLE ACT_RU_TASK ADD CONSTRAINT ACT_FK_TASK_EXE FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_TASK_PROCINST ON ACT_RU_TASK (PROC_INST_ID_);

ALTER TABLE ACT_RU_TASK ADD CONSTRAINT ACT_FK_TASK_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_TASK_PROCDEF ON ACT_RU_TASK (PROC_DEF_ID_);

ALTER TABLE ACT_RU_TASK ADD CONSTRAINT ACT_FK_TASK_PROCDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);

CREATE INDEX ACT_IDX_VAR_EXE ON ACT_RU_VARIABLE (EXECUTION_ID_);

ALTER TABLE ACT_RU_VARIABLE ADD CONSTRAINT ACT_FK_VAR_EXE FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_VAR_PROCINST ON ACT_RU_VARIABLE (PROC_INST_ID_);

ALTER TABLE ACT_RU_VARIABLE ADD CONSTRAINT ACT_FK_VAR_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_VAR_BYTEARRAY ON ACT_RU_VARIABLE (BYTEARRAY_ID_);

ALTER TABLE ACT_RU_VARIABLE ADD CONSTRAINT ACT_FK_VAR_BYTEARRAY FOREIGN KEY (BYTEARRAY_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_JOB_EXCEPTION ON ACT_RU_JOB (EXCEPTION_STACK_ID_);

ALTER TABLE ACT_RU_JOB ADD CONSTRAINT ACT_FK_JOB_EXCEPTION FOREIGN KEY (EXCEPTION_STACK_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_EVENT_SUBSCR ON ACT_RU_EVENT_SUBSCR (EXECUTION_ID_);

ALTER TABLE ACT_RU_EVENT_SUBSCR ADD CONSTRAINT ACT_FK_EVENT_EXEC FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_MODEL_SOURCE ON ACT_RE_MODEL (EDITOR_SOURCE_VALUE_ID_);

ALTER TABLE ACT_RE_MODEL ADD CONSTRAINT ACT_FK_MODEL_SOURCE FOREIGN KEY (EDITOR_SOURCE_VALUE_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_MODEL_SOURCE_EXTRA ON ACT_RE_MODEL (EDITOR_SOURCE_EXTRA_VALUE_ID_);

ALTER TABLE ACT_RE_MODEL ADD CONSTRAINT ACT_FK_MODEL_SOURCE_EXTRA FOREIGN KEY (EDITOR_SOURCE_EXTRA_VALUE_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_MODEL_DEPLOYMENT ON ACT_RE_MODEL (DEPLOYMENT_ID_);

ALTER TABLE ACT_RE_MODEL ADD CONSTRAINT ACT_FK_MODEL_DEPLOYMENT FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES ACT_RE_DEPLOYMENT (ID_);

